/**********************************************************************
 * Extern for AmazonCognitoIdentity
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var AmazonCognitoIdentity = {
  "CognitoAccessToken": function () {},
  "CognitoAuth": function () {},
  "CognitoAuthSession": function () {},
  "CognitoIdToken": function () {},
  "CognitoRefreshToken": function () {},
  "CognitoTokenScopes": function () {},
  "DateHelper": function () {},
  "StorageHelper": function () {}
};
/**********************************************************************
 * End Generated Extern for AmazonCognitoIdentity
/**********************************************************************/
